from cell_matrix import CellMatrix
from cell_state import CellState

first_genration = CellMatrix()

first_genration.update_cell_unit(0, 0, CellState.ALIVE)
first_genration.update_cell_unit(1, 1, CellState.ALIVE)
first_genration.update_cell_unit(2, 2, CellState.ALIVE)
first_genration.update_cell_unit(3, 3, CellState.ALIVE)
first_genration.update_cell_unit(4, 4, CellState.ALIVE)


first_genration.update_cell_unit(0, 4, CellState.ALIVE)
first_genration.update_cell_unit(1, 3, CellState.ALIVE)
first_genration.update_cell_unit(2, 2, CellState.ALIVE)
first_genration.update_cell_unit(3, 1, CellState.ALIVE)
first_genration.update_cell_unit(4, 0, CellState.ALIVE)

# print(first_genration.get_values_grid())
# print(first_genration.get_state_grid())

print("1")
print(first_genration.get_pretty_grid())
next_generation = first_genration.evolve()
print("2")
print(next_generation.get_pretty_grid())
next_generation = next_generation.evolve()
print("3")
print(next_generation.get_pretty_grid())
next_generation = next_generation.evolve()
print("4")
print(next_generation.get_pretty_grid())
next_generation = next_generation.evolve()
print("5")
print(next_generation.get_pretty_grid())
next_generation = next_generation.evolve()
print("6")
print(next_generation.get_pretty_grid())
next_generation = next_generation.evolve()
print("7")
print(next_generation.get_pretty_grid())
next_generation = next_generation.evolve()
print("8")
print(next_generation.get_pretty_grid())
next_generation = next_generation.evolve()
print("9")
print(next_generation.get_pretty_grid())
next_generation = next_generation.evolve()
print("10")
print(next_generation.get_pretty_grid())
next_generation = next_generation.evolve()
print("11")
print(next_generation.get_pretty_grid())